### ISSUE TITLE
Connecting extra UARTs and NICs 

### ISSUE THREAD

**Issue by vit9696** [YetAnotherMod/qemu#15]
Hello,

In order to use more than one serial adapter and connect network adapters to sockets the following patches were needed on our side:

- [ppc-ppc476fp-nic.patch](https://github.com/YetAnotherMod/qemu/files/13444534/ppc-ppc476fp-nic.patch)
- [ppc-ppc476fp-serial.patch](https://github.com/YetAnotherMod/qemu/files/13444535/ppc-ppc476fp-serial.patch)

Would you consider merging them?

**Comment by nia40m** [comment]
Applied your patches with some changes.
In patсh with serial devices I also added an interrupt lines connection to the MPIC.
In patch with network devices I changed the order of `nd_table` indexes. In MB115.01 board `greth[1]` and `gbit_greth[1]` are used as main one so they should be connected to `nd_table[0]`.
